[project]
name="bpy-stubs"
version="3.0.0"

# Don't export any of the modules we define here
[tool.setuptools]
py-modules = []

[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"